// Report generation: console summary, Markdown, and a self-contained HTML page.

const sevIcon = { high: '🔴', medium: '🟠', low: '🟡', info: 'ℹ️' };
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function consoleSummary(ctx) {
  const { url, scores, findings, vis, serp } = ctx;
  const lines = [];
  lines.push('');
  lines.push(`  Findable audit — ${url}`);
  lines.push(`  Overall ${scores.overall}/100 (${scores.grade}) · AI readability ${scores.readability} · AI access ${scores.access} · Search visibility ${scores.visibility}`);
  lines.push('');
  for (const c of vis.checks) {
    if (c.error) { lines.push(`  ⚠ search "${c.query}" failed: ${c.error}`); continue; }
    const tops = (c.topResults || []).map((r) => r.host).filter(Boolean).slice(0, 3);
    lines.push(`  ${c.found ? `#${c.position}` : '—'}  ${c.label}: "${c.query}"${c.found || !tops.length ? '' : `  (top: ${tops.join(', ')})`}`);
  }
  if (serp) lines.push(serp.ok
    ? `  live ${serp.engine}: ${serp.target_found ? `found at #${serp.target_position}` : 'not in top 10'}`
    : `  live SERP check skipped/failed: ${serp.error || 'disabled'}`);
  lines.push('');
  const top = findings.filter((f) => f.severity !== 'info').slice(0, 8);
  for (const f of top) lines.push(`  ${sevIcon[f.severity]} [${f.area}] ${f.title}`);
  if (findings.length > top.length) lines.push(`  … ${findings.length - top.length} more in the full report`);
  return lines.join('\n');
}

export function markdownReport(ctx) {
  const { url, when, scores, findings, a, vis, serp, queries } = ctx;
  const md = [];
  md.push(`# Findable audit — ${url}`);
  md.push(`\n*Audited live on ${when} · powered by TinyFish Search, Fetch${serp ? ' and Agent' : ''}*`);
  md.push(`\n## Scores\n`);
  md.push(`| Overall | AI readability | AI access | Search visibility |`);
  md.push(`|---|---|---|---|`);
  md.push(`| **${scores.overall}/100 (${scores.grade})** | ${scores.readability} | ${scores.access} | ${scores.visibility} |`);

  md.push(`\n## What AI tools see on this page\n`);
  md.push(`- Raw HTML (plain crawler view): **${a.content.rawWords} words**`);
  md.push(`- TinyFish Fetch extraction (AI view): **${a.content.tfWords} words** (parity ratio ${a.content.parityRatio})`);
  md.push(`- Title seen by AI: ${a.content.tfTitle ? `"${a.content.tfTitle}"` : '*(none)*'}`);
  md.push(`- h1: ${a.headings.h1 ? `"${a.headings.h1}"` : '*(missing)*'} · structured data: ${a.jsonLdTypes.length ? a.jsonLdTypes.join(', ') : '*(none)*'}`);
  md.push(`- AI crawler access: ${a.access.blockedBots.length === 0 ? 'all major AI bots allowed' : `**${a.access.blockedBots.length} blocked** (${a.access.blockedBots.map((b) => b.bot).join(', ')})`}`);
  md.push(`- robots.txt: ${a.access.robotsPresent ? 'present' : 'absent'} · sitemap.xml: ${a.access.sitemap ? 'present' : 'absent'} · llms.txt: ${a.access.llmsTxt ? 'present' : 'absent'}`);
  if (a.content.tfExcerpt) {
    md.push(`\n<details><summary>Extraction excerpt (first 1,200 chars of what an AI reads)</summary>\n\n\`\`\`\n${a.content.tfExcerpt}\n\`\`\`\n</details>`);
  }

  md.push(`\n## Where it surfaces in search\n`);
  for (const c of vis.checks) {
    if (c.error) { md.push(`- ⚠ "${c.query}" — search failed (${c.error})`); continue; }
    md.push(`\n### ${c.label}: "${c.query}" — ${c.found ? `**position ${c.position}**` : '**not in results**'}\n`);
    md.push(`| # | Result | Domain |`);
    md.push(`|---|---|---|`);
    for (const r of c.topResults || []) {
      const you = r.host === vis.host ? ' **← you**' : '';
      md.push(`| ${r.position} | ${r.title?.slice(0, 80) || ''} | ${r.host}${you} |`);
    }
    if (c.myResult?.snippet) md.push(`\nYour snippet: *"${c.myResult.snippet}"*`);
  }
  if (serp) {
    md.push(`\n### Live SERP cross-check (TinyFish Agent on ${serp.engine})\n`);
    if (serp.ok) {
      md.push(serp.target_found
        ? `A real browser search confirms **${vis.host} appears at position ${serp.target_position}**.`
        : `A real browser search confirms **${vis.host} is absent from the first 10 live results**.`);
      if (Array.isArray(serp.results) && serp.results.length) {
        md.push(`\n| # | Result | Domain |`);
        md.push(`|---|---|---|`);
        for (const r of serp.results.slice(0, 10)) md.push(`| ${r.position} | ${esc(r.title).slice(0, 80)} | ${r.domain} |`);
      }
    } else {
      md.push(`Live check unavailable this run: ${serp.error}`);
    }
  }

  md.push(`\n## Findings & fixes (${findings.filter((f) => f.severity !== 'info').length})\n`);
  for (const f of findings) {
    md.push(`\n### ${sevIcon[f.severity]} ${f.severity.toUpperCase()} · ${f.area} — ${f.title}\n`);
    md.push(`${f.why}\n`);
    md.push(`**Fix:**\n\n\`\`\`\n${f.fix}\n\`\`\``);
  }

  md.push(`\n---\n*Generated by [Findable](https://github.com/johnnycool1000/findable). Queries audited: ${queries.map((q) => `"${q.q}"`).join(', ')}.*`);
  return md.join('\n');
}

export function htmlReport(ctx) {
  const { url, when, scores, findings, a, vis, serp } = ctx;
  const ring = (label, val) => `<div class="ring"><div class="num">${val}</div><div class="lbl">${label}</div></div>`;
  const rows = (list) => list.map((r) => `<tr><td>${r.position}</td><td>${esc(r.title)}</td><td>${esc(r.host || r.domain)}${(r.host || r.domain) === vis.host ? ' <b>← you</b>' : ''}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Findable audit — ${esc(url)}</title>
<style>
:root{--bg:#0e1116;--card:#161b24;--txt:#e6e9ef;--mut:#8b93a7;--acc:#35c2a0;--hi:#ff5d5d;--md:#ffab40;--lo:#ffd84d}
*{box-sizing:border-box}body{margin:0;font:15px/1.6 system-ui,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--txt);padding:32px 16px}
.wrap{max-width:880px;margin:0 auto}h1{font-size:22px}h2{margin-top:36px;border-bottom:1px solid #242b38;padding-bottom:6px}
.scores{display:flex;gap:14px;flex-wrap:wrap;margin:20px 0}.ring{background:var(--card);border-radius:14px;padding:16px 22px;text-align:center;min-width:120px}
.num{font-size:30px;font-weight:700;color:var(--acc)}.lbl{color:var(--mut);font-size:12px}
.find{background:var(--card);border-radius:12px;padding:14px 18px;margin:12px 0;border-left:4px solid var(--mut)}
.find.high{border-color:var(--hi)}.find.medium{border-color:var(--md)}.find.low{border-color:var(--lo)}
.find h3{margin:0 0 6px;font-size:15px}.find .why{color:var(--mut)}
pre{background:#0a0d12;padding:12px;border-radius:8px;overflow-x:auto;font-size:13px;white-space:pre-wrap}
table{border-collapse:collapse;width:100%;margin:10px 0}td,th{padding:6px 10px;border-bottom:1px solid #242b38;text-align:left;font-size:14px}
.tag{display:inline-block;background:#232a38;color:var(--mut);border-radius:20px;padding:2px 10px;font-size:12px;margin-right:6px}
a{color:var(--acc)}</style></head><body><div class="wrap">
<h1>Findable audit — ${esc(url)}</h1>
<div style="color:var(--mut)">Audited live on ${esc(when)} · TinyFish Search + Fetch${serp ? ' + Agent' : ''}</div>
<div class="scores">${ring('Overall', `${scores.overall} (${scores.grade})`)}${ring('AI readability', scores.readability)}${ring('AI access', scores.access)}${ring('Search visibility', scores.visibility)}</div>
<h2>What AI tools see</h2>
<p><span class="tag">raw HTML: ${a.content.rawWords} words</span><span class="tag">AI extraction: ${a.content.tfWords} words</span><span class="tag">parity ${a.content.parityRatio}</span><span class="tag">h1: ${esc(a.headings.h1 || 'missing')}</span><span class="tag">JSON-LD: ${a.jsonLdTypes.length ? esc(a.jsonLdTypes.join(', ')) : 'none'}</span><span class="tag">blocked AI bots: ${a.access.blockedBots.length}</span></p>
<h2>Search visibility</h2>
${vis.checks.map((c) => c.error ? `<p>⚠ "${esc(c.query)}": ${esc(c.error)}</p>` : `<h3>${esc(c.label)}: “${esc(c.query)}” — ${c.found ? `position ${c.position}` : 'not in results'}</h3><table><tr><th>#</th><th>Result</th><th>Domain</th></tr>${rows(c.topResults || [])}</table>`).join('')}
${serp && serp.ok ? `<h3>Live SERP (${esc(serp.engine)} via TinyFish Agent) — ${serp.target_found ? `found at #${serp.target_position}` : 'absent from top 10'}</h3><table><tr><th>#</th><th>Result</th><th>Domain</th></tr>${rows((serp.results || []).slice(0, 10))}</table>` : ''}
<h2>Findings &amp; fixes</h2>
${findings.map((f) => `<div class="find ${f.severity}"><h3>${f.severity.toUpperCase()} · ${esc(f.area)} — ${esc(f.title)}</h3><div class="why">${esc(f.why)}</div><pre>${esc(f.fix)}</pre></div>`).join('')}
<p style="color:var(--mut);margin-top:40px">Generated by <a href="https://github.com/johnnycool1000/findable">Findable</a>.</p>
</div></body></html>`;
}
